// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6oPIeexTOKVf-1pjBfl5GOyJWvmujuuM',
    appId: '1:79183484515:web:a270b4ad3e02305d504a56',
    messagingSenderId: '79183484515',
    projectId: 'socialapp-2b607',
    authDomain: 'socialapp-2b607.firebaseapp.com',
    storageBucket: 'socialapp-2b607.firebasestorage.app',
    measurementId: 'G-4EV1YMZ3M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF4BxLyvjaB9uxB8fAcmwdQCzzoEmXi84',
    appId: '1:79183484515:android:e479ecd3d170d986504a56',
    messagingSenderId: '79183484515',
    projectId: 'socialapp-2b607',
    storageBucket: 'socialapp-2b607.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTYxVv4aHT3CJXhwIBCJ3xMU9swoTx35w',
    appId: '1:79183484515:ios:e8ee3e469b18bb07504a56',
    messagingSenderId: '79183484515',
    projectId: 'socialapp-2b607',
    storageBucket: 'socialapp-2b607.firebasestorage.app',
    iosBundleId: 'com.example.mySocialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTYxVv4aHT3CJXhwIBCJ3xMU9swoTx35w',
    appId: '1:79183484515:ios:e8ee3e469b18bb07504a56',
    messagingSenderId: '79183484515',
    projectId: 'socialapp-2b607',
    storageBucket: 'socialapp-2b607.firebasestorage.app',
    iosBundleId: 'com.example.mySocialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6oPIeexTOKVf-1pjBfl5GOyJWvmujuuM',
    appId: '1:79183484515:web:ecd4a626423cfd5d504a56',
    messagingSenderId: '79183484515',
    projectId: 'socialapp-2b607',
    authDomain: 'socialapp-2b607.firebaseapp.com',
    storageBucket: 'socialapp-2b607.firebasestorage.app',
    measurementId: 'G-ZCET5NR2E4',
  );
}
